### ISSUE TITLE
needs to be updated to discordjs v13

### ISSUE THREAD

**Issue by FuriousLeech** [diegowinter/LegendaryDJ#1]

**Comment by FuriousLeech** [comment]
well i guess it works without error however when i play a song, the bot joins the call and immediately leaves without playing.

**Comment by diegowinter** [comment]
I've tested here and it's working fine. If you are testing locally on your machine, be sure if FFmpeg is installed and added to PATH.
About Discord.js, I've started an update, but there are many changes in v13 and it'll take some time to release a new version with it.

**Comment by FuriousLeech** [comment]
> I've tested here and it's working fine. If you are testing locally on your machine, be sure if FFmpeg is installed and added to PATH.
> About Discord.js, I've started an update, but there are many changes in v13 and it'll take some time to release a new version with it.

just added ffmpeg to the path, and still no success. joins, and then leaves. am i supposed to have a specific version of ffmpeg? Edit: got it working, i had added FFmpeg to the path, however i had to also add ffmpeg to the bot folder, and make a new path with that location. works perfect. thank you
