### ISSUE TITLE
O que é o parâmetro "cookie"?

### ISSUE THREAD

**Issue by luiz-olsen** [diegowinter/LegendaryDJ#2]

**Comment by diegowinter** [comment]
Olá, este parâmetro serve para ser passado um cookie contendo uma sessão logada do YouTube, que ajuda a reduzir os erros em que o YouTube reconhece o acesso do bot como uma atividade suspeita. [Neste exemplo](https://github.com/fent/node-ytdl-core/blob/master/example/cookies.js), no início, tem um comentário ensinando como obter os cookies usando o navegador.
